# Pytorch Notebook

In [5]:
import torch
import torchvision
import numpy as np

## Pytorch basics

In [16]:
x = torch.ones(3, 4)

print(x)
print(x.view(1, 12))
print(x.view(2, -1))

y = torch.rand(3, 4)
z = x + y

print(z.size())
print(z)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
torch.Size([3, 4])
tensor([[1.7880, 1.6233, 1.7106, 1.1526],
        [1.6345, 1.1149, 1.2167, 1.6470],
        [1.1962, 1.2656, 1.3082, 1.1896]])


In [21]:
x = torch.ones(1, requires_grad=True)
print(x)



tensor([1.], requires_grad=True)


## Autograd and some specific topics

In [ ]:
# Utilities


### Define Fully Connected Feed Forward NN $f_{\theta}$ 

In [4]:
x = torch.randn(5)


print(x)

tensor([ 0.6864, -0.6671, -1.8042, -1.0444,  0.7582])


### Calculate Loss $L(\theta)$

### Calculate $\nabla_\theta L(\theta, x)|_{x=x_0}$

### Calculate $\nabla_x L(\theta, x)|_{x=x_0}$

### Update $\theta \leftarrow \theta + \alpha \nabla_\theta L(\theta, x)|_{x=x_0}$

### Update weight by minibatch $\frac{1}{N} \sum_{n=1}^N \nabla_\theta L(\theta, x)|_{x=x_n}$

### Update $x \leftarrow x + \alpha \nabla_x L(\theta, x)|_x$

### Copy $\theta_1$ to $\theta_2$

### Copy $\theta_1$ to $\theta_2$ and update only $\theta_1$ by $\theta \leftarrow \theta + \alpha \nabla_\theta L(\theta, x)|_{x=x_0}$

### Stochastic sampling from $f_\theta(x)$

### Inject noise (reparametrization trick) and cal grad $\nabla_\theta f_\theta(x, \epsilon)$, $\epsilon\sim {\cal N}(\mu, \sigma^2)$

### Use weighted update $\theta \leftarrow \theta + \alpha \delta \nabla_\theta L(\theta, x)|_{x=x_0}$, $\delta  = f_\theta(x) - \theta_0$

### Use noisy weight $f(x, \theta + \epsilon)$, $\epsilon \sim {\cal N}(1, 0)$

### Update $\theta$ by the approximated variational method

# Convolution Neural Networks

### Define CNN $f_\theta(x)$

### Update weight by minibatch for CNN

### Update $x \leftarrow x + \alpha \nabla_x L(\theta, x)|_x$ for CNN

# Recurrent Neural Networks

### Define RNN $f_\theta(x_0, x_1, \dots, x_T)$

### Update weight by minibatch for RNN

### Update $x \leftarrow x + \alpha \nabla_x L(\theta, x)|_x$ for RNN